Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,20 +2,42 @@ name: CI
 
 on: [push]
 
-
 jobs:
   build:
     runs-on: self-hosted
     steps:
-     - name: Check out the repo
-       run: rm -rf diatoz_assinment && git clone https://github.com/vinaybv77716/diatoz_assinment.git
-     - name: Check docker version
-       run: sudo apt-get update
-     # - name: build docker image and push to ecr repo
-     #   run: |
-     #      sudo apt update
-     #      sudo chown $USER /var/run/docker.sock
-     #      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 890405391444.dkr.ecr.us-east-1.amazonaws.com
-     #      docker build -t nodeproj diatoz_assinment/.
-     #      docker tag nodeproj:latest 890405391444.dkr.ecr.us-east-1.amazonaws.com/nodeproj:latest
-     #      docker push 890405391444.dkr.ecr.us-east-1.amazonaws.com/nodeproj:latest
+      - name: Check out the repo
+        run: |
+          rm -rf diatoz_assinment
+          git clone https://github.com/vinaybv77716/diatoz_assinment.git
+
+      - name: Check and install Docker if not present
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found. Installing Docker..."
+            sudo apt-get update
+            sudo apt-get install -y ca-certificates curl gnupg
+            sudo install -m 0755 -d /etc/apt/keyrings
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+            echo \
+              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+            sudo apt-get update
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+          else
+            echo "Docker is already installed"
+          fi
+
+      - name: Check and install AWS CLI if not present
+        run: |
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found. Installing AWS CLI..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI is already installed"
+          fi
