Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,17 +20,57 @@ jobs:
           else
             echo "terraform-eks repo already exists. Skipping clone."
           fi  
-
-    
-      
+      - name: Check and install Terraform if not present
+        run: |
+          if ! command -v terraform &> /dev/null
+          then
+            echo "Terraform not found. Installing Terraform..."
+            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
+            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
+            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+            sudo apt-get update && sudo apt-get install terraform -y
+          else
+            echo "Terraform is already installed"
+          fi
+      - name: Check and install Docker if not present
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found. Installing Docker..."
+            sudo apt-get update
+            sudo apt-get install -y ca-certificates curl gnupg
+            sudo install -m 0755 -d /etc/apt/keyrings
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+            echo \
+              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+            sudo apt-get update
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+          else
+            echo "Docker is already installed"
+          fi
+      - name: Check and install AWS CLI if not present
+        run: |
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found. Installing AWS CLI..."
+            sudo apt install unzip -y
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI is already installed"
+          fi      
       - name: Configure AWS CLI
         run: |
-          sudo sh terraform-eks/prerequisites.sh 
           echo "aws configure"
           aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
           aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
           aws configure set default.region "${{ secrets.AWS_REGION }}"
           aws configure set output json
+          echo "#######  testing  #######"
+          aws s3 ls  
       - name: build docker image and push to ecr repo
         run: |
           sudo apt update
@@ -44,21 +84,44 @@ jobs:
         run: |
          cd terraform-eks/ && terraform init 
          terraform plan
-
-            read -p "Do you want to run terraform plan? (y/n): " confirm
-            if [[ "$confirm" == "y" ]]; then
-            terraform plan
-            else
-            echo "Skipping terraform plan"
-            fi
-        #  terraform apply -auto-approve
-     
+         terraform apply 
+      - name: Install kubectl if not present
+        run: |
+          echo "#######   kubectl    ######"
+          if ! command -v kubectl &> /dev/null; then
+            echo "kubectl not found. Installing..."
+            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
+            chmod +x ./kubectl
+            sudo mv ./kubectl /usr/local/bin
+          else
+            echo "kubectl is already installed: $(kubectl version --short --client)"
+          fi
+      - name: Install eksctl if not present
+        run: |
+         echo "#######   eksctl    ######"
+         if ! command -v eksctl &> /dev/null; then
+         echo "eksctl not found. Installing..."
+         curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
+         sudo mv /tmp/eksctl /usr/local/bin
+         else
+         echo "eksctl is already installed: $(eksctl version)"
+         fi
       - name: update kubeconfig
         run: |
           echo "#######   kubeconfig    ######"
           aws eks  update-kubeconfig --region us-east-1 --name my-eks-cluster
           kubectl get pods -A
-
+      - name: Install Helm if not present
+        run: |
+          echo "#######   Checking Helm   ######"
+          if ! command -v helm &> /dev/null; then
+            echo "Helm not found. Installing..."
+             curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+             chmod 700 get_helm.sh
+             ./get_helm.sh
+          else
+            echo "Helm already installed: $(helm version --short)"
+          fi
       
       - name: OIDC and IAM Service Account setup if not already done
         run: |
@@ -79,13 +142,20 @@ jobs:
             echo "Creating service account and attaching policies..."
             eksctl create iamserviceaccount --name vinay --namespace kube-system --cluster my-eks-cluster --role-name vinay-role \
             --attach-policy-arn arn:aws:iam::aws:policy/AdministratorAccess --approve --override-existing-serviceaccounts
-
-             eksctl create iamidentitymapping --cluster  my-eks-cluster --region=us-east-1 --arn "arn:aws:iam::200901485389:user/project-ciq-poc" --group system:masters --username admin
           fi
       
           # Output service account info
           kubectl get sa vinay -n kube-system -o yaml
- 
+      - name: Add EKS Helm repo if not already added
+        run: |
+          echo "#######   Helm repo check   ######"
+          if helm repo list | grep -q '^eks'; then
+            echo "EKS Helm repo already exists"
+          else
+            echo "Adding EKS Helm repo"
+            helm repo add eks https://aws.github.io/eks-charts
+          fi
+          helm repo update
       
       - name: Install AWS Load Balancer Controller if not already installed
         run: |
@@ -102,3 +172,4 @@ jobs:
           fi
       
       
+Update main.yml · vinaybv77716/kool@b2059ce 
