Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,13 +85,18 @@ jobs:
          cd terraform-eks/ && terraform init 
          terraform plan
          terraform apply -auto-approve
-      - name: install kubectl
+      - name: Install kubectl if not present
         run: |
           echo "#######   kubectl    ######"
-          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
-          chmod +x ./kubectl
-          sudo mv ./kubectl /usr/local/bin
-          kubectl version --short --client
+          if ! command -v kubectl &> /dev/null; then
+            echo "kubectl not found. Installing..."
+            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
+            chmod +x ./kubectl
+            sudo mv ./kubectl /usr/local/bin
+          else
+            echo "kubectl is already installed: $(kubectl version --short --client)"
+          fi
+      
       - name: update kubeconfig
         run: |
           echo "#######   kubeconfig    ######"
